### ISSUE TITLE
请求修改代码以适配torch新的版本

### ISSUE THREAD

**Issue by shushan2017** [ZhiningLiu1998/mesa#11]
查资料torch1.4.0以后的版本会报错
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [50, 1]], which is output 0 of AsStridedBackward0, is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

1.4.0是比较老的版本了 好像不支持python3.9 所以请求修改mesa的代码以适配新的torch 
谢谢大神！！！

**Comment by nevereverforget1** [comment]
您解决这个问题了吗？跟告诉我有社么比较好的解决办法吗？
