### ISSUE TITLE
Not able to run the model

### ISSUE THREAD

**Issue by semese** [ZhiningLiu1998/mesa#2]
Hi,

I've been trying to run your mesa_example notebook, however, I haven't managed to make it work. When the meta_fit() method is called, I'm getting a RuntimeError. I've tried debugging it, but without any luck. Here is a screenshot of the problem:

![Screenshot 2021-08-18 at 12 54 42](https://user-images.githubusercontent.com/9866463/129886224-a89db332-b572-46f8-9f5b-27bc92f36e71.png)

Have you encountered this? If yes, could you please tell me how to fix it? 

Thanks in advance!

**Comment by semese** [comment]
Hi again, 

Never mind, I found the issue. It wasn't the code, but one of the dependencies, that I haven't noticed wasn't matching. Sorry for opening an issue...

**Comment by ZhiningLiu1998** [comment]
Hi, semese

It’s okay and I would like to thank you for your interest in our work. Your issue made me notice something that can be improved. So I made some minor updates, including adding a short guide for setting up the environment in the README. Hope this helps you and others. 

If you have any further questions, please feel free to open an issue or drop me an email.

Best

**Comment by pipilurj** [comment]
> Hi again,
> 
> Never mind, I found the issue. It wasn't the code, but one of the dependencies, that I haven't noticed wasn't matching. Sorry for opening an issue...

Hi semese, could you tell me which dependency cause the problem? I've got the same issue here.

**Comment by semese** [comment]
> 

Hi! I'm sorry, I really don't remember anymore what was it. In the end I ended up creating a new environment from scratch and installing first only the required packages, then adding the other things I was using. This way it worked out.

**Comment by ZhiningLiu1998** [comment]
> > Hi again,
> > Never mind, I found the issue. It wasn't the code, but one of the dependencies, that I haven't noticed wasn't matching. Sorry for opening an issue...
> 
> Hi semese, could you tell me which dependency cause the problem? I've got the same issue here.

Hi Renjie,

It is most likely caused by the PyTorch version inconsistency (the SAC implementation requires an older version of PyTorch (v1.0.0)). As semese said, you may want to create a new environment from scratch. I have provided a short guide in the README that you may find helpful, please see [requirements](https://github.com/ZhiningLiu1998/mesa#requirements).
