### ISSUE TITLE
在多分类任务下报错

### ISSUE THREAD

**Issue by rickyxume** [ZhiningLiu1998/mesa#3]
我尝试直接修改源代码中的工具类utils.py，完全按照load_dataset的方式读取了自己的数据集，在Rater类下的score函数里加上了acc和micro f1_score尝试做多分类下的评估，用y_pred.argmax(axis=1)来确定预测类别，但是要么维度不匹配，要么就返回`TypeError: Singleton array 4 cannot be considered a valid collection.`.，请问有没有多分类的usage案例可供学习使用？

**Comment by ZhiningLiu1998** [comment]
Hi Ricky

感谢提问。

**MESA的整体设计是针对传统二分类问题的**，包括元状态的设计以及采样策略都是假设只有一个少数类以及一个多数类。向多分类问题的扩展是non-intuitive的（参考原论文：https://arxiv.org/pdf/2010.08830.pdf ）。

另外，你可以尝试 
1）使用分解策略将多分类问题转换为多个二分类问题的组合，然后在每个子问题上使用mesa。
2）尝试另一个方法SPE：https://github.com/ZhiningLiu1998/self-paced-ensemble ，SPE是支持多分类的。
3）尝试我开发的一个package：https://github.com/ZhiningLiu1998/imbalanced-ensemble ，这个package里实现了包括SMOTEBoost/Bagging等一系列集成不平衡分类方法，全部方法都支持多分类，以及一些高级特性（如，训练日志、自定义采样目标、重采样scheduler等）。若有兴趣的话可以参考源码的实现。

希望能帮到你。

Best,
Zhining

**Comment by rickyxume** [comment]
> Hi Ricky
> 
> 感谢提问。
> 
> **MESA的整体设计是针对传统二分类问题的**，包括元状态的设计以及采样策略都是假设只有一个少数类以及一个多数类。向多分类问题的扩展是non-intuitive的（参考原论文：https://arxiv.org/pdf/2010.08830.pdf ），所以可能不能实现对多分类的直接支持。
> 
> 但你可以尝试 ：
> 1）使用分解策略将多分类问题转换为多个二分类问题的组合，然后在每个子问题上使用mesa。
> 2）尝试另一个方法SPE：https://github.com/ZhiningLiu1998/self-paced-ensemble ，SPE是支持多分类的。
> 3）尝试我开发的一个package：https://github.com/ZhiningLiu1998/imbalanced-ensemble ，这个package里实现了包括SMOTEBoost/Bagging等一系列集成不平衡分类方法，全部方法都支持多分类，以及一些高级特性（如，训练日志、自定义采样目标、重采样scheduler等）。若有兴趣的话可以参考源码的实现。
> 
> 希望能帮到你。
> 
> Best,
> Zhining

感谢回复！我也使用了其它的不平衡学习方法包括SPE，看到知乎专栏里介绍的这篇论文对比SPE有提升所以就想试一试，另外感谢你每次都大晚上回复，早点休息 : )
