### ISSUE TITLE
数据贴标签以及train_ir设置问题

### ISSUE THREAD

**Issue by JieWang-EEG** [ZhiningLiu1998/mesa#8]
[作者你好，很荣幸能够接触您整理和开源的这个项目。手上正好有一个数据不均衡的多分类项目，我尝试了imbalanced-ensemble中所有的方法，对于我的项目并没有太好的提升。所以想试试这个元学习，之前没有接触过元学习，因为项目急急可能没法去补充详细知识，问的问题可能有点。。。。

是这样的，我把我的数据转换成多个二分类来适应这个项目。但是在运行时，在train_ir有点问题。这个图片的代码是需要0是多数类，1是少数类嘛？不然得需要用train_ir来控制吧？同时这里的imbalance ratio是期望多数类比少数类吧？

同时想问下，对于离散特征数据，多分类数据重叠和不均衡有没有很什么好方法可以推荐下。

最后，再感谢大佬开源的项目。祝您身体健康，合家欢乐。

![xx](https://user-images.githubusercontent.com/97270458/148646881-62a10d61-59d2-4763-9c34-67a83fbfaacf.png)

**Comment by JieWang-EEG** [comment]
> 

对了，作者。这个是environment.py中load_data()的部分函数

**Comment by ZhiningLiu1998** [comment]
你好，感谢你对我们工作的关注~

是的，默认是少数类为正类，imbalance ratio是期望多数类比少数类。

我有几点建议：
- imbalanced ensemble里面提供的集成学习方法默认使用决策树作为**基分类器**，正则化项也都是sklearn的默认设置（max_depth=None，boosting类方法max_depth=1），如果所有方法效果都不好的话，你可能需要先确定决策树适不适合你的分类任务。换句话说，要先找到一个合理的分类器，再去加对于类别不平衡的处理。可能的选项有：sklearn里的各种分类器，xgboost，lightgbm，catboost等。
- 除了集成方法，还可以尝试其他package里提供的预处理方法，比如imbalanced learn和smote-variants
- lightgbm处理离散特征很方便，并且有内部的优化，可以尝试一下

一切算法的基础都是数据，我还是建议先搞清楚自己的任务数据的特点，再确定重点需要解决的问题是什么：数据不平衡？噪声？类别重叠？特征稀疏？特征冗余？等等。问题常常会出现在没考虑到的地方。

链接：
imbalanced learn： https://imbalanced-learn.org/stable/
smote-variants： https://smote-variants.readthedocs.io/en/latest/getting_started.html

**Comment by JieWang-EEG** [comment]
> 你好，感谢你对我们工作的关注~
> 
> 是的，默认是少数类为正类，imbalance ratio是期望多数类比少数类。
> 
> 我有几点建议：
> 
> * imbalanced ensemble里面提供的集成学习方法默认使用决策树作为**基分类器**，正则化项也都是sklearn的默认设置（max_depth=None，boosting类方法max_depth=1），如果所有方法效果都不好的话，你可能需要先确定决策树适不适合你的分类任务。换句话说，要先找到一个合理的分类器，再去加对于类别不平衡的处理。可能的选项有：sklearn里的各种分类器，xgboost，lightgbm，catboost等。
> * 除了集成方法，还可以尝试其他package里提供的预处理方法，比如imbalanced learn和smote-variants
> * lightgbm处理离散特征很方便，并且有内部的优化，可以尝试一下
> 
> 一切算法的基础都是数据，我还是建议先搞清楚自己的任务数据的特点，再确定重点需要解决的问题是什么：数据不平衡？噪声？类别重叠？特征稀疏？特征冗余？等等。问题常常会出现在没考虑到的地方。
> 
> 链接： imbalanced learn： https://imbalanced-learn.org/stable/ smote-variants： https://smote-variants.readthedocs.io/en/latest/getting_started.html

感谢回复！的确我有很多问题没有考虑到，对于您的建议我好好学习一下！
