### ISSUE TITLE
MESA训练集与其他模型的训练集不一样

### ISSUE THREAD

**Issue by MarielMa** [ZhiningLiu1998/mesa#9]
为什么MESA模型的训练集是 train+valid,其他模型的训练集只有train,并没有用到valid? 这样还有可比性吗?

**Comment by ZhiningLiu1998** [comment]
你好，感谢提问。

首先，**MESA的训练集不是train+valid**，你可以仔细阅读论文中的算法2和算法3，其中D_t是train set，D_v是valid set。
- train set: 算法2（ensemble training）的第7、8行描述了选取基学习器训练集的过程，你可以看到采样的是D_t，用于训练数据的是D_t的子集D'_t，i.e., D_v的数据并没用用于训练任何预测模型。
- valid set: D_v在算法2（ensemble training）中只出现在4、5行，用于计算误差分布E_Dv和meta-state S_t，D_v在算法3（meta training）中只出现在line#6，用于计算reward（泛化性能的变化）。

你混淆了两个做法：“训练时使用train和valid” 和 “将train+valid作为训练集“
- “训练时使用train和valid”：验证集本来的作用就是用来在训练的时候选取模型的最优设置，所以正常情况下的模型训练也会用到valid set。
- 而你说的“将train+valid作为训练集“意味着不区分train+valid，直接把两者取并集作为train set扔给模型训练，这肯定是不对的。将valid set的内容放入训练集意味着用了训练集的一个子集选取超参数，这么做没有意义，并且如上所诉，也不是MESA的做法。

另：
- 在meta-sampler的训练中使用了valid set的信息（比如用于计算meta-state和reward）用于指导teacher model什么是”good action“，但并没有直接从valid set数据特征直接学习信息（meta-sampler的输入空间是固定的状态空间，不是原始特征空间）。
- 你可以将meta/teacher model的角色理解为调参的机器学习工程师，所以它们需要valid set的信息。在MESA论文的相关工作中有关meta learning的部分，你能找到更多元学习的工作，它们的teacher model也使用了valid set上的gradient，如[1][2]

[1] Mengye Ren, Wenyuan Zeng, Bin Yang, and Raquel Urtasun. Learning to reweight examples for robust deep learning. In International Conference on Machine Learning, pages 4334–4343, 2018.
[2] Jun Shu, Qi Xie, Lixuan Yi, Qian Zhao, Sanping Zhou, Zongben Xu, and Deyu Meng. Meta-weight-net: Learning an explicit mapping for sample weighting. In NeurIPS, 2019.
